### ISSUE TITLE
El comando "/bus" no muestra las estimaciones de parada

### ISSUE THREAD

**Issue by MaanuelMM** [CoreDumped-ETSISI/uni-services#1]
¡Hola!

Debido un cambio en la API de la EMT de Madrid sin previo aviso, las estimaciones de tiempo del bus ya no se muestran en el bot al ser usada la API antigua.

Por ello, le adjunto la [nueva documentación de la API](https://apidocs.emtmadrid.es/), en donde  destaco la [obtención del token](https://apidocs.emtmadrid.es/#api-Block_1_User_identity-login) y la [obtención de estimación de tiempos](https://apidocs.emtmadrid.es/#api-Block_3_TRANSPORT_BUSEMTMAD-arrives).

Siento no poder ayudar en más, ya que no tengo mucha idea de "Go".

Saludos.

**Comment by Guad** [comment]
Gracias! Le echaré un ojo
